name: build
on: [push]
jobs:
  build:
    runs-on: macos-26
    steps:
    - uses: SwiftyLab/setup-swift@latest
    - uses: actions/checkout@main
    - name: Get Swift version
      run: swift --version
    - name: Build
      run: swift build
    - name: Test
      run: swift test --enable-code-coverage
  codecov:
    container:
      image: swift:6.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: swift test --enable-test-discovery --enable-code-coverage
    - uses: mattpolzin/swift-codecov-action@0.7.5
      with:
        MINIMUM_COVERAGE: 98
        INCLUDE_TESTS: 'true'
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}