name: build and test
on: [push]
jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: SwiftyLab/setup-swift@latest
    - uses: actions/checkout@main
    - name: Get Swift version
      run: swift --version
    - name: Build
      run: swift build
    - name: Test
      run: swift test --enable-code-coverage
